import avatarSrc1 from "./image/avatar/avatar-1.jpg"
import avatarSrc2 from "./image/avatar/avatar-2.jpg"
import avatarSrc3 from "./image/avatar/avatar-3.jpg"
import avatarSrc4 from "./image/avatar/avatar-4.jpg"
import avatarSrc5 from "./image/avatar/avatar-5.jpg"
import avatarSrc6 from "./image/avatar/avatar-6.jpg"
import avatarSrc7 from "./image/avatar/avatar-7.jpg"
import avatarSrc8 from "./image/avatar/avatar-8.jpg"
import avatarSrc9 from "./image/avatar/avatar-9.jpg"
import avatarSrc10 from "./image/avatar/avatar-10.jpg"
import avatarSrc11 from "./image/avatar/avatar-11.jpg"
import avatarSrc12 from "./image/avatar/avatar-12.jpg"

import cardSrc1 from "./image/cards/1.png"
import cardSrc2 from "./image/cards/2.png"
import cardSrc3 from "./image/cards/3.png"
import cardSrc4 from "./image/cards/4.png"
import cardSrc5 from "./image/cards/5.png"
import cardSrc6 from "./image/cards/6.png"
import cardSrc7 from "./image/cards/7.png"
import cardSrc8 from "./image/cards/8.png"
import cardSrc9 from "./image/cards/9.png"
import cardSrc10 from "./image/cards/10.png"
import cardSrc11 from "./image/cards/11.png"
import cardSrc12 from "./image/cards/12.png"
import cardSrc13 from "./image/cards/13.png"
import cardSrc14 from "./image/cards/14.png"
import cardSrc15 from "./image/cards/15.png"
import cardSrc16 from "./image/cards/16.png"
import cardSrc17 from "./image/cards/17.png"
import cardSrc18 from "./image/cards/18.png"
import cardSrc19 from "./image/cards/19.png"
import cardSrc20 from "./image/cards/20.png"
import cardSrc21 from "./image/cards/21.png"
import cardSrc22 from "./image/cards/22.png"
import cardSrc23 from "./image/cards/23.png"
import cardSrc24 from "./image/cards/24.png"
import cardSrc25 from "./image/cards/25.png"
import cardSrc26 from "./image/cards/26.png"
import cardSrc27 from "./image/cards/27.png"
import cardSrc28 from "./image/cards/28.png"
import cardSrc29 from "./image/cards/29.png"
import cardSrc30 from "./image/cards/30.png"
import cardSrc31 from "./image/cards/31.png"
import cardSrc32 from "./image/cards/32.png"
import cardSrc33 from "./image/cards/33.png"
import cardSrc34 from "./image/cards/34.png"
import cardSrc35 from "./image/cards/35.png"
import cardSrc36 from "./image/cards/36.png"
import cardSrc37 from "./image/cards/37.png"
import cardSrc38 from "./image/cards/38.png"
import cardSrc39 from "./image/cards/39.png"
import cardSrc40 from "./image/cards/40.png"
import cardSrc41 from "./image/cards/41.png"
import cardSrc42 from "./image/cards/42.png"
import cardSrc43 from "./image/cards/43.png"
import cardSrc44 from "./image/cards/44.png"
import cardSrc45 from "./image/cards/45.png"
import cardSrc46 from "./image/cards/46.png"
import cardSrc47 from "./image/cards/47.png"
import cardSrc48 from "./image/cards/48.png"
import cardSrc49 from "./image/cards/49.png"
import cardSrc50 from "./image/cards/50.png"
import cardSrc51 from "./image/cards/51.png"
import cardSrc52 from "./image/cards/52.png"
import cardSrc53 from "./image/cards/53.png"
import cardSrc54 from "./image/cards/54.png"
import cardSrc55 from "./image/cards/55.png"
import cardSrc56 from "./image/cards/56.png"
import cardSrc57 from "./image/cards/57.png"
import cardSrc58 from "./image/cards/58.png"
import cardSrc59 from "./image/cards/59.png"
import cardSrc60 from "./image/cards/60.png"
import cardSrc61 from "./image/cards/61.png"
import cardSrc62 from "./image/cards/62.png"
import cardSrc63 from "./image/cards/63.png"
import cardSrc64 from "./image/cards/64.png"
import cardSrc65 from "./image/cards/65.png"
import cardSrc66 from "./image/cards/66.png"
import cardSrc67 from "./image/cards/67.png"
import cardSrc68 from "./image/cards/68.png"
import cardSrc69 from "./image/cards/69.png"
import cardSrc70 from "./image/cards/70.png"
import cardSrc71 from "./image/cards/71.png"
import cardSrc72 from "./image/cards/72.png"
import cardSrc73 from "./image/cards/73.png"
import cardSrc74 from "./image/cards/74.png"
import cardSrc75 from "./image/cards/75.png"
import cardSrc76 from "./image/cards/76.png"
import cardSrc77 from "./image/cards/77.png"
import cardSrc78 from "./image/cards/78.png"
import cardSrc79 from "./image/cards/79.png"
import cardSrc80 from "./image/cards/80.png"
import cardSrc81 from "./image/cards/81.png"
import cardSrc82 from "./image/cards/82.png"
import cardSrc83 from "./image/cards/83.png"
import cardSrc84 from "./image/cards/84.png"
import cardSrc85 from "./image/cards/85.png"
import cardSrc86 from "./image/cards/86.png"
import cardSrc87 from "./image/cards/87.png"
import cardSrc88 from "./image/cards/88.png"
import cardSrc89 from "./image/cards/89.png"
import cardSrc90 from "./image/cards/90.png"
import cardSrc91 from "./image/cards/91.png"
import cardSrc92 from "./image/cards/92.png"
import cardSrc93 from "./image/cards/93.png"
import cardSrc94 from "./image/cards/94.png"
import cardSrc95 from "./image/cards/95.png"
import cardSrc96 from "./image/cards/96.png"
import cardSrc97 from "./image/cards/97.png"
import cardSrc98 from "./image/cards/98.png"
import cardSrc99 from "./image/cards/99.png"
import cardSrc100 from "./image/cards/100.png"
import cardSrc101 from "./image/cards/101.png"
import cardSrc102 from "./image/cards/102.png"
import cardSrc103 from "./image/cards/103.png"
import cardSrc104 from "./image/cards/104.png"
import cardSrc105 from "./image/cards/105.png"
import cardSrc106 from "./image/cards/106.png"
import cardSrc107 from "./image/cards/107.png"
import cardSrc108 from "./image/cards/108.png"
import Lavcraft from "./image/cards/Lavcraft.png"
import Necronomicon from "./image/cards/Necronomicon.png"
import cardSrc110 from "./image/cards/event.png"
import cardSrc111 from "./image/cards/panic.png"

export const GAME_PLAYER = {
  PLAYER_1: "player-1",
  PLAYER_2: "player-2",
  PLAYER_3: "player-3",
  PLAYER_4: "player-4",
  PLAYER_5: "player-5",
  PLAYER_6: "player-6",
  PLAYER_7: "player-7",
  PLAYER_8: "player-8",
  PLAYER_9: "player-9",
  PLAYER_10: "player-10",
  PLAYER_11: "player-11",
  PLAYER_12: "player-12",
}

export const MOVE_PLAYER = [
  GAME_PLAYER.PLAYER_1,
  GAME_PLAYER.PLAYER_2,
  GAME_PLAYER.PLAYER_3,
  GAME_PLAYER.PLAYER_4,
  GAME_PLAYER.PLAYER_5,
  GAME_PLAYER.PLAYER_6,
  GAME_PLAYER.PLAYER_7,
  GAME_PLAYER.PLAYER_8,
  GAME_PLAYER.PLAYER_9,
  GAME_PLAYER.PLAYER_10,
  GAME_PLAYER.PLAYER_11,
  GAME_PLAYER.PLAYER_12,
]

export const PLAYERS = [
  {
    id: 1,
    name: "Макриди",
    avatar: avatarSrc1,
    player: GAME_PLAYER.PLAYER_1,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 2,
    name: "Ноулс",
    avatar: avatarSrc2,
    player: GAME_PLAYER.PLAYER_2,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 3,
    name: "Чайлдс",
    avatar: avatarSrc3,
    player: GAME_PLAYER.PLAYER_3,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 4,
    name: "Вэнс Норрис",
    avatar: avatarSrc4,
    player: GAME_PLAYER.PLAYER_4,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 5,
    name: "Dog Thing",
    avatar: avatarSrc5,
    player: GAME_PLAYER.PLAYER_5,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 6,
    name: "Джордж Беннингс",
    avatar: avatarSrc6,
    player: GAME_PLAYER.PLAYER_6,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 7,
    name: "Палмер",
    avatar: avatarSrc7,
    player: GAME_PLAYER.PLAYER_7,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 8,
    name: "Фьюкс",
    avatar: avatarSrc8,
    player: GAME_PLAYER.PLAYER_8,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 9,
    name: "Доктор Коппер",
    avatar: avatarSrc9,
    player: GAME_PLAYER.PLAYER_9,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 10,
    name: "Норвежец",
    avatar: avatarSrc10,
    player: GAME_PLAYER.PLAYER_10,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 11,
    name: "Гэрри",
    avatar: avatarSrc11,
    player: GAME_PLAYER.PLAYER_11,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
  {
    id: 12,
    name: "Виндоус",
    avatar: avatarSrc12,
    player: GAME_PLAYER.PLAYER_12,
    statistic: {
      gameThing: 0,
      winThing: 0,
      gameSurvivor: 0,
      winSurvivor: 0,
      gameInfected: 0,
      winInfected: 0,
      allGames: 0,
      allWins: 0,
      allLosses: 0,
    },
  },
]

export const CARDS = [
  {
    id: 1,
    name: "Нечто",
    image: cardSrc1,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "blocked",
  },
  {
    id: 2,
    name: "Заражение",
    image: cardSrc2,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 3,
    name: "Заражение",
    image: cardSrc3,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 4,
    name: "Заражение",
    image: cardSrc4,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 5,
    name: "Заражение",
    image: cardSrc5,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 6,
    name: "Заражение",
    image: cardSrc6,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 7,
    name: "Заражение",
    image: cardSrc7,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 8,
    name: "Заражение",
    image: cardSrc8,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 9,
    name: "Заражение",
    image: cardSrc9,
    pack: 4,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 10,
    name: "Заражение",
    image: cardSrc10,
    pack: 6,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 11,
    name: "Заражение",
    image: cardSrc11,
    pack: 7,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 12,
    name: "Заражение",
    image: cardSrc12,
    pack: 7,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 13,
    name: "Заражение",
    image: cardSrc13,
    pack: 7,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 14,
    name: "Заражение",
    image: cardSrc14,
    pack: 8,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 15,
    name: "Заражение",
    image: cardSrc15,
    pack: 9,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 16,
    name: "Заражение",
    image: cardSrc16,
    pack: 9,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 17,
    name: "Заражение",
    image: cardSrc17,
    pack: 10,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 18,
    name: "Заражение",
    image: cardSrc18,
    pack: 10,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 19,
    name: "Заражение",
    image: cardSrc19,
    pack: 11,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 20,
    name: "Заражение",
    image: cardSrc20,
    pack: 11,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 21,
    name: "Заражение",
    image: cardSrc21,
    pack: 11,
    property: "событие",
    transfer: false,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 22,
    name: "Огнемёт",
    image: cardSrc22,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 23,
    name: "Огнемёт",
    image: cardSrc23,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 24,
    name: "Огнемёт",
    image: cardSrc24,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 25,
    name: "Огнемёт",
    image: cardSrc25,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 26,
    name: "Огнемёт",
    image: cardSrc26,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 27,
    name: "Анализ",
    image: cardSrc27,
    pack: 5,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 28,
    name: "Анализ",
    image: cardSrc28,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 29,
    name: "Анализ",
    image: cardSrc29,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 30,
    name: "Топор",
    image: cardSrc30,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 31,
    name: "Топор",
    image: cardSrc31,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 32,
    name: "Подозрение",
    image: cardSrc32,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 33,
    name: "Подозрение",
    image: cardSrc33,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 34,
    name: "Подозрение",
    image: cardSrc34,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 35,
    name: "Подозрение",
    image: cardSrc35,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 36,
    name: "Подозрение",
    image: cardSrc36,
    pack: 7,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 37,
    name: "Подозрение",
    image: cardSrc37,
    pack: 8,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 38,
    name: "Подозрение",
    image: cardSrc38,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 39,
    name: "Подозрение",
    image: cardSrc39,
    pack: 10,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 40,
    name: "Виски",
    image: cardSrc40,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 41,
    name: "Виски",
    image: cardSrc41,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 42,
    name: "Виски",
    image: cardSrc42,
    pack: 10,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 43,
    name: "Упорство",
    image: cardSrc43,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 44,
    name: "Упорство",
    image: cardSrc44,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 45,
    name: "Упорство",
    image: cardSrc45,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 46,
    name: "Упорство",
    image: cardSrc46,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 47,
    name: "Упорство",
    image: cardSrc47,
    pack: 10,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 48,
    name: "Гляди по сторонам",
    image: cardSrc48,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 49,
    name: "Гляди по сторонам",
    image: cardSrc49,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
    areaUse: "toMyself",
  },
  {
    id: 50,
    name: "Меняемся местами",
    image: cardSrc50,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 51,
    name: "Меняемся местами",
    image: cardSrc51,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 52,
    name: "Меняемся местами",
    image: cardSrc52,
    pack: 7,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 53,
    name: "Меняемся местами",
    image: cardSrc53,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 54,
    name: "Меняемся местами",
    image: cardSrc54,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "nearby",
  },
  {
    id: 55,
    name: "Сматывай удочки",
    image: cardSrc55,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 56,
    name: "Сматывай удочки",
    image: cardSrc56,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 57,
    name: "Сматывай удочки",
    image: cardSrc57,
    pack: 7,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 58,
    name: "Сматывай удочки",
    image: cardSrc58,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 59,
    name: "Сматывай удочки",
    image: cardSrc59,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 60,
    name: "Соблазн",
    image: cardSrc60,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 61,
    name: "Соблазн",
    image: cardSrc61,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 62,
    name: "Соблазн",
    image: cardSrc62,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 63,
    name: "Соблазн",
    image: cardSrc63,
    pack: 7,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 64,
    name: "Соблазн",
    image: cardSrc64,
    pack: 8,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 65,
    name: "Соблазн",
    image: cardSrc65,
    pack: 10,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 66,
    name: "Соблазн",
    image: cardSrc66,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: true,
    status: "active",
    areaUse: "everyBody",
  },
  {
    id: 67,
    name: "Страх",
    image: cardSrc67,
    pack: 5,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 68,
    name: "Страх",
    image: cardSrc68,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 69,
    name: "Страх",
    image: cardSrc69,
    pack: 8,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 70,
    name: "Страх",
    image: cardSrc70,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 71,
    name: "Мне и здесь неплохо",
    image: cardSrc71,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 72,
    name: "Мне и здесь неплохо",
    image: cardSrc72,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 73,
    name: "Мне и здесь неплохо",
    image: cardSrc73,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 74,
    name: "Нет уж, спасибо",
    image: cardSrc74,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 75,
    name: "Нет уж, спасибо",
    image: cardSrc75,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 76,
    name: "Нет уж, спасибо",
    image: cardSrc76,
    pack: 8,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 77,
    name: "Нет уж, спасибо",
    image: cardSrc77,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 78,
    name: "Мимо",
    image: cardSrc78,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 79,
    name: "Мимо",
    image: cardSrc79,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 80,
    name: "Мимо",
    image: cardSrc80,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 81,
    name: "Никакого шашлыка",
    image: cardSrc81,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 82,
    name: "Никакого шашлыка",
    image: cardSrc82,
    pack: 6,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 83,
    name: "Никакого шашлыка",
    image: cardSrc83,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "disabled",
  },
  {
    id: 84,
    name: "Карантин",
    image: cardSrc84,
    pack: 5,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 85,
    name: "Карантин",
    image: cardSrc85,
    pack: 9,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 86,
    name: "Заколоченная дверь",
    image: cardSrc86,
    pack: 4,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 87,
    name: "Заколоченная дверь",
    image: cardSrc87,
    pack: 7,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 88,
    name: "Заколоченная дверь",
    image: cardSrc88,
    pack: 11,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 89,
    name: "Старые верёвки",
    image: cardSrc89,
    pack: 6,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 90,
    name: "Старые верёвки",
    image: cardSrc90,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 91,
    name: "Раз,два",
    image: cardSrc91,
    pack: 5,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 92,
    name: "Раз,два",
    image: cardSrc92,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 93,
    name: "Три,четыре",
    image: cardSrc93,
    pack: 4,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 94,
    name: "Три,четыре",
    image: cardSrc94,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 95,
    name: "И это вы называете вечеринкой",
    image: cardSrc95,
    pack: 5,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 96,
    name: "И это вы называете вечеринкой",
    image: cardSrc96,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 97,
    name: "Убирайся прочь",
    image: cardSrc97,
    pack: 5,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 98,
    name: "Забывчивость",
    image: cardSrc98,
    pack: 4,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 99,
    name: "Цепная реакция",
    image: cardSrc99,
    pack: 4,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: true,
    status: "active",
  },
  {
    id: 100,
    name: "Цепная реакция",
    image: cardSrc100,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: true,
    status: "active",
  },
  {
    id: 101,
    name: "Давай дружить",
    image: cardSrc101,
    pack: 7,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 102,
    name: "Давай дружить",
    image: cardSrc102,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 103,
    name: "Свидание вслепую",
    image: cardSrc103,
    pack: 4,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: true,
    status: "active",
  },
  {
    id: 104,
    name: "Свидание вслепую",
    image: cardSrc104,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: true,
    status: "active",
  },
  {
    id: 105,
    name: "Уупс",
    image: cardSrc105,
    pack: 10,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 106,
    name: "Только между нами",
    image: cardSrc106,
    pack: 7,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 107,
    name: "Только между нами",
    image: cardSrc107,
    pack: 9,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 108,
    name: "Время признаний",
    image: cardSrc108,
    pack: 8,
    property: "паника",
    transfer: false,
    shirt: cardSrc111,
    canBlocked: false,
    status: "active",
  },
  {
    id: 109,
    name: "Некрономикон",
    image: Necronomicon,
    pack: 100,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
  {
    id: 110,
    name: "Лавкрафт",
    image: Lavcraft,
    pack: 200,
    property: "событие",
    transfer: true,
    shirt: cardSrc110,
    canBlocked: false,
    status: "active",
  },
]
